{
 "title": "Drift User Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "'CUhCSd7jHvycC89L6EqMoDWcWVTXXHhAeXVyB4362qZg'"
   }
  ]
 },
 "panels": [
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Drift Users Buying Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  buying_power\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
    }
   ]
  },
  {
   "title": "Drift Users Margin Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  margin_ratio\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
    }
   ]
  },
  {
   "title": "Drift Users Leverage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  leverage\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
    }
   ]
  },
  {
   "title": "Drift Users Total Collateral",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  total_collateral\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
    }
   ]
  },
  {
   "title": "Drift Users Total Position Value",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  total_position_value\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
    }
   ]
  },
  {
   "title": "Drift Users Free Collateral",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  free_collateral\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drift Users Buying Power",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  buying_power\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
      }
     ]
    },
    {
     "title": "Drift Users Buying Power",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  buying_power\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
      }
     ]
    },
    {
     "title": "Drift Users Leverage",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  leverage\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
      }
     ]
    },
    {
     "title": "Drift Users Total Collateral",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  total_collateral\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
      }
     ]
    },
    {
     "title": "Drift Users Margin Ratio",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  margin_ratio\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
      }
     ]
    },
    {
     "title": "Drift Users Free Collateral",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  published_time AS \"time\",\n  public_key, \n  free_collateral\nFROM drift_user_position\nWHERE\n  $__timeFilter(published_time) AND\n  public_key = ${user:text}"
      }
     ]
    }
   ]
  }
 ]
}