apiVersion: 1
deleteDatasources: []
datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    database: drift
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: "disable"
